server:
  port: 8086
  servlet:
    context-path: /book

spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/book-service?authSource=admin
      auto-index-creation: true

app:
  services:
    profile:
      url: http://localhost:8081/profile
    identity:
      url: http://localhost:8080/identity
